@startuml

interface ExchangeRateRepository {
  getSpotPrice(fromCurrency: string, toCurrency: string): Promise<number>
}

ExchangeRateController --> ExchangeRateService: uses
ExchangeRateService --> ExchangeRateRepository: uses

ExchangeRateRepository <|-- HostExchangeRateRepository: implements
HostExchangeRateRepository --> HostExchangeClient: uses

ExchangeRateRepository <|-- FreeCurrencyConversionExchangeRateRepository: implements
FreeCurrencyConversionExchangeRateRepository --> FreeCurrencyConversionClient: uses

@enduml